const demonyms = [
  "Andorran",
  "Emirian",
  "Emirati",
  "Afghani",
  "Afghan",
  "Antiguan",
  "Anguillan",
  "Albanian",
  "Alabanian",
  "Armenian",
  "Hayastani",
  "Angolan",
  "Antarctic",
  "Argentine",
  "Argentinian",
  "Argentinean",
  "Samoan",
  "Austrian",
  "Australian",
  "Arubia",
  "Ålandic",
  "Ålandish",
  "Azerbaijani",
  "Bosnian",
  "Herzegovinian",
  "Barbadian",
  "Barbadan",
  "Bajan",
  "Bangladeshi",
  "Belgian",
  "Burkinabe",
  "Bulgarian",
  "Bahrainian",
  "Burundian",
  "Beninese",
  "Barthélemois",
  "Bermudan",
  "Bruneian",
  "BolivianBrazilian",
  "Bahameese",
  "Bahamian",
  "Bhutanese",
  "Motswana",
  "Batswana",
  "Belarusian",
  "Belizean",
  "Brazilian",
  "Canadian",
  "Cocossian",
  "Cocos Islandia",
  "Congolese",
  "Central African",
  "Congolese",
  "Swiss",
  "Ivorian",
  "Cook Islander",
  "Chilean",
  "Cameroonian",
  "Chinese",
  "Colombian",
  "Columbian",
  "Costa Rican",
  "Cuban",
  "Cape Verdean",
  "Curaçaoan",
  "Christmas Islander",
  "Cypriot",
  "Czech",
  "German",
  "Djiboutian",
  "Djibouti",
  "Danish",
  "Dane",
  "Dominican",
  "Dominican",
  "Algerian",
  "Ecuadorean",
  "Ecudorean",
  "Estonian",
  "Egyptian",
  "Western Saharan",
  "Sahrawi",
  "Eritrean",
  "Spanish",
  "Ethiopian",
  "Finnish",
  "Fijian",
  "Falkland Islander",
  "Micronesian",
  "Faroese",
  "French",
  "Gabonese",
  "British",
  "Grenadian",
  "Georgian",
  "French Guianese",
  "Ghanaian",
  "Ghanian",
  "Gibraltarian",
  "Greenlander",
  "Greenlandic",
  "Gambian",
  "Guinean",
  "Guadeloupean",
  "Equatorial Guinean",
  "Equatoguinean",
  "Greek",
  "Guatemalan",
  "Guamanian",
  "Guinean",
  "Guyanese",
  "Hong Konger",
  "Honduran",
  "Croatian",
  "Croat",
  "Haitian",
  "Hungarian",
  "Indonesian",
  "Irish",
  "Israeli",
  "Manx",
  "Indian",
  "Iraqi",
  "Iranian",
  "Icelander",
  "Italian",
  "Jamaican",
  "Jordanian",
  "Japanese",
  "Kenyan",
  "Kyrgyzstani",
  "Cambodian",
  "I-Kiribati",
  "Comoran",
  "Kittian",
  "Nevisian",
  "North Korean",
  "South Korean",
  "Kuwaiti",
  "Caymanian",
  "Kazakhstani",
  "Kazakh",
  "Laotian",
  "Lebanese",
  "Saint Lucian",
  "Liechtensteiner",
  "Sri Lankan",
  "Liberian",
  "Mosotho",
  "Basotho",
  "Lithunian",
  "Luxembourger",
  "Latvian",
  "Libyan",
  "Moroccan",
  "Monacan",
  "Moldovan",
  "Montenegrin",
  "Malagasy",
  "Marshallese",
  "Macedonian",
  "Malian",
  "Myanmarese",
  "Burmese",
  "Mongolian",
  "Macanese",
  "Northern Mariana Islander",
  "Martinican",
  "Martiniquaís",
  "Mauritanian",
  "Montserratian",
  "Maltese",
  "Mauritian",
  "Maldivan",
  "Malawian",
  "Mexican",
  "Malaysian",
  "Mozambican",
  "Namibian",
  "New Caledonian",
  "New Caledonians",
  "Nigerien",
  "Norfolk Islander",
  "Nigerian",
  "Nicaraguan",
  "Nicoya",
  "Dutch",
  "Norwegian",
  "Nepalese",
  "Nauruan",
  "Niuean",
  "New Zealander",
  "Omani",
  "Panamanian",
  "Peruvian",
  "French Polynesian",
  "Papua New Guinean",
  "Filipino",
  "Pakistani",
  "Polish",
  "Pole",
  "Saint-Pierrais",
  "Miquelonnais",
  "Pitcairn Islander",
  "Puerto Rican",
  "Palestinian",
  "Portuguese",
  "Portugese",
  "Palauan",
  "Paraguayan",
  "Qatari",
  "Romanian",
  "Serbian",
  "Serb",
  "Russian",
  "Rwandan",
  "Rwandese",
  "Saudi Arabian",
  "Saudi",
  "Solomon Islander",
  "Seychellois",
  "Sudanese",
  "Swedish",
  "Swede",
  "Singaporean",
  "Saint Helenian",
  "Slovenian",
  "Slovene",
  "Slovakian",
  "Slovak",
  "Sierra Leonean",
  "Sanmarinese",
  "Sammarinese",
  "Senegalese",
  "Somali",
  "Surinamer",
  "Surinamese",
  "Sudanese",
  "São Tomean",
  "Sao Tomean",
  "Salvadorean",
  "Salvadoran",
  "Syrian",
  "Swazi",
  "Turks and Caicos Islander",
  "Chadian",
  "Togolese",
  "Thai",
  "Tajikistani",
  "Tokelauan",
  "Timorese",
  "Turkmen",
  "Tunisian",
  "Tongan",
  "Turkish",
  "Turk",
  "Trinidadian",
  "Tobagonian",
  "Tuvaluan",
  "Taiwanese",
  "Tanzanian",
  "Ukrainian",
  "Ugandan",
  "American",
  "Uruguayan",
  "Uzbekistani",
  "Saint Vincentian",
  "Vincentian",
  "Venezuelan",
  "Virgin Islander",
  "Virgin Islander",
  "Vietnamese",
  "Ni-Vanuatu",
  "Wallisian",
  "Futunan",
  "Samoan",
  "Yemeni",
  "Yemenese",
  "Mahoran",
  "South African",
  "Zambian",
  "Zimbabwean",
];
exports.demonyms = demonyms;
